version: '2'
services:
    gestiontaches-app:
        image: gestiontaches
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gestiontaches-postgresql:5432/gestionTaches
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gestiontaches-postgresql:
        extends:
            file: postgresql.yml
            service: gestiontaches-postgresql
